# -*- coding: utf-8 -*-
"""mental_health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_4jaHecoQVXcm57EpoK_5n_5ety8O6m
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from statsmodels.discrete.discrete_model import MNLogit
# Install stepmix if not already installed
!pip install stepmix
from stepmix.stepmix import StepMix
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import pandas as pd



# Specify the path to your DTA file in Google Drive
# Replace 'Your_Folder/your_file.dta' with the actual path
file_path = '/content/drive/MyDrive/data (1)/Husband’s_characteristics_women’s work_women’s_empowerment.dta'
file_path2 = '/content/drive/MyDrive/data (1)/mental_health_copy.dta'
file_path3 = '/content/drive/MyDrive/data (1)/Woman’s characteristics.dta'

# Read the DTA file into a pandas DataFrame
dfwomen_char = pd.read_stata(file_path3)
# Read the DTA file into a pandas DataFrame
dfmental_health = pd.read_stata(file_path2)
# Read the DTA file into a pandas DataFrame
df = pd.read_stata(file_path)

# Display the first few rows of the DataFrame
print(df.head())

df.shape

dfmental_health.shape

dfwomen_char.shape

"""# MERGE 3 FILE

"""

merged_df = pd.concat([dfmental_health, df, dfwomen_char], axis=1)
merged_df.shape

"""#MISSING VALUE

"""

#pd.set_option('display.max_rows', None)
# Calculate the total count of missing values for each column
missing_count = merged_df.isnull().sum()

# Calculate the percentage of missing values for each column
# df.isnull().mean() returns the proportion (0.0 to 1.0)
missing_percentage = merged_df.isnull().mean() * 100

# Create a summary DataFrame for a clear view (optional, but helpful)
missing_data_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing Percentage (%)': missing_percentage
})

# Display the result
print("\nMissing Value Summary:")
print(missing_data_summary)

"""#DROPPING MISSING Columns 40% OR MORE

"""

# Define your threshold (e.g., drop columns with >= 50% missing values)
threshold_percent4 = 40

# Get the list of column names to drop

columns_to_drop4 = missing_percentage[missing_percentage >= threshold_percent4].index.tolist()
print(f"\nColumns to drop (>= {threshold_percent4}% missing): {columns_to_drop4}")


# Drop the identified columns from the DataFrame
# axis=1 indicates we are dropping columns
# inplace=True modifies the original DataFrame
df40 = merged_df.drop(columns=columns_to_drop4)
print("\nDataFrame after dropping variables:")

df40.shape

"""#DROP ROWs with MISSING VALUES"""

# Drop rows that have ANY missing values
df_cleaned_missing4 = df40.dropna(axis=0, how='any')
print('df40 shape',df_cleaned_missing4.shape)
df_cleaned_missing4.head()

"""#CONVERT INTO DATAFRAME"""

df_cleaned_missing4 = pd.DataFrame(df_cleaned_missing4)

"""# DISTINCT VALUES IN COLUMN"""

df_cleaned_missing4['mth1'].unique()

# Iterate through each column in the DataFrame
variable_list = []
for col in df_cleaned_missing4.columns:
    # Check if the column contains numerical data (integers or floats)
    #if pd.api.types.is_numeric_dtype(df_cleaned_missing4[col]):
        # Get the distinct values in the column
        distinct_values = df_cleaned_missing4[col].unique()

        # Get the count of distinct values
        distinct_count = len(distinct_values)
        if distinct_count > 6:
          print(f"column :{col} have :{distinct_count} distinct value")
          # Varibale list which have more than 6 distinct value
          variable_list.append(col)
print(variable_list)

"""# Variables_names

# Mental Health Variables

| Name | Label |
|---|---|
| mth1 | last 2 weeks: feeling nervous anxious, on edge |
| mth2 | last 2 weeks: not able to stop/control worrying |
| mth3 | last 2 weeks: worrying about things |
| mth4 | last 2 weeks: trouble relaxing |
| mth5 | last 2 weeks: restless and hard to sit still |
| mth6 | last 2 weeks: become easily annoyed/irritable |
| mth7 | last 2 weeks: feeling afraid as something awful might happen |
| mth8 | last 2 weeks: little interest/pleasure in doing things |
| mth9 | last 2 weeks: feeling down, depressed or hopeless |
| mth10 | last 2 weeks: trouble falling asleep or sleeping too much |
| mth11 | last 2 weeks: feeling tired or having little energy |
| mth12 | last 2 weeks: poor appetite or overeating |
| mth13 | last 2 weeks: feeling bad about yourself, you are a failure or let yourself or f |
| mth14 | last 2 weeks: trouble concentrating in reading or watching tv |
| mth15 | last 2 weeks: moving/speaking slowly or moving around a lot more than ... |
| mth16 | last 2 weeks: thoughts of better off dead or hurting yourself |
| mth19 | ever been told by a doctor/health care worker you have: depression |
| mth20 | ever been told by a doctor/health care worker you have: anxiety |
| mth21 | last 2 weeks took medication prescribed by doctor/health worker for depr... |
| mth22 | phq score |
| mth23 | referral based on phq score |
| mth24 | gad score |

# Husband Characteristics

| Name | Label |
|---|---|
| v701 | husband/partner's education level |
| v702 | husband/partner's highest year of education (at level in v701) |
| v704 | husband/partner's occupation |
| v704a | husband/partner worked in last 7 days/12 months |
| v705 | husband/partner's occupation (grouped) |
| v714 | respondent currently working |
| v715 | husband/partner's total number of years of education |
| v716 | respondent's occupation |
| v717 | respondent's occupation (grouped) |
| v729 | husband/partner's educational attainment |
| v730 | husband/partner's age |
| v731 | respondent worked in last 12 months |
| v743a | person who usually decides on: respondent's health care |
| v743b | person who usually decides on: large household purchases |
| v743d | person who usually decides on: visits to family or relatives |
| v743f | person who usually decides on: what to do with money husband earns |
| v744a | beating justified if wife goes out without telling husband |
| v744b | beating justified if wife neglects the children |
| v744c | beating justified if wife argues with husband |
| v744d | beating justified if wife refuses to have sex with husband |
| v744e | beating justified if wife burns the food |
| v745a | owns a house alone or jointly |
| v745b | owns land alone or jointly |

# Women Characteristics

| Name | Label |
|---|---|
| v101 | division |
| v102 | type of place of residence |
| v104 | years lived in place of residence |
| v105 | type of place of previous residence |
| v106 | highest educational level |
| v107 | highest year of education |
| v113 | source of drinking water |
| v116 | type of toilet facility |
| v119 | household has: electricity |
| v120 | household has: radio |
| v121 | household has: television |
| v122 | household has: refrigerator |
| v123 | household has: bicycle |
| v124 | household has: motorcycle/scooter |
| v125 | household has: car/truck |
| v127 | main floor material |
| v128 | main wall material |
| v129 | main roof material |
| v130 | religion |
| v133 | education in single years |
| v134 | de facto place of residence |
| v135 | usual resident or visitor |
| v136 | number of household members (listed) |
| v137 | number of children 5 and under in household (de jure) |
| v138 | number of eligible women in household (de facto) |
| v139 | de jure region of residence |
| v140 | de jure type of place of residence |
| v141 | de jure place of residence |
| v149 | educational attainment |
| v150 | relationship to household head |
| v151 | sex of household head |
| v152 | age of household head |
| v153 | household has: telephone (land-line) |
| v155 | literacy |
| v157 | frequency of reading newspaper or magazine |
| v158 | frequency of listening to radio |
| v159 | frequency of watching television |
| v160 | toilet facilities shared with other households |
| v169a | owns a mobile telephone |
| v169b | last 12 months use mobile telephone for financial transactions |
| v169c | is respondent's mobile phone a smart phone |
| v170 | has an account in a bank or other financial institution |
| v171a | use of internet |
| v175 | reason for moving to current palce of residence |
| v190a |  wealth index for urban and rura |
| v191a | wealth index factor score for urban/rural(decimels) |

# MEASURE OF ASSOCIATION
"""

import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

def calculate_cramers_v(chi2_stat, n, min_dim):
    """Calculate Cramér's V statistic."""
    if min_dim == 0:
        return 0.0
    # Use max(0, min_dim) to avoid issues if dimension is 1
    return np.sqrt(chi2_stat / (n * max(1, min_dim)))

def run_chi_square_for_all_columns(df, target_col_name, alpha=0.05):
    """
    Runs Chi-Square tests for ALL other columns in the DataFrame against a single
    target variable and returns results in a pandas DataFrame.
    """
    # Automatically get all columns to test (exclude the target column itself)
    list_of_vars_to_test = [col for col in df.columns if col != target_col_name]

    results_list = []

    for test_var in list_of_vars_to_test:
        # Create contingency table
        contingency_table = pd.crosstab(df[test_var], df[target_col_name])
        n = contingency_table.sum().sum()

        # Check for sufficient categories (chi2 requires at least 2x2 table logic)
        if min(contingency_table.shape) < 2:
            print(f"Skipping '{test_var}' vs '{target_col_name}' due to insufficient categories (need at least 2 categories in both variables).")
            continue

        # Calculate stats
        chi2_stat, p_value, dof, expected_counts = chi2_contingency(contingency_table)

        # Determine significance
        significance = "Significant" if p_value < alpha else "Non-Significant"

        # Calculate Cramer's V (strength of association)
        cramers_v = calculate_cramers_v(chi2_stat, n, min(contingency_table.shape)-1)

        # Identify highest/lowest percentages for each column in the target variable
        col_percent_df = pd.crosstab(df[test_var], df[target_col_name], normalize='columns') * 100

        highest_pct_info = {}
        lowest_pct_info = {}
        for column in col_percent_df.columns:
            highest_idx = col_percent_df[column].idxmax()
            highest_val = col_percent_df[column].max()
            lowest_idx = col_percent_df[column].idxmin()
            lowest_val = col_percent_df[column].min()

            highest_pct_info[column] = f"'{highest_idx}' ({highest_val:.1f}%)"
            lowest_pct_info[column] = f"'{lowest_idx}' ({lowest_val:.1f}%)"

        # Append all results as a single row to our list
        results_list.append({
            'Variable Tested': test_var,
            'P-value': round(p_value, 5),
            'Significance Decision (alpha=0.05)': significance,
            'Cramers V (Association Strength)': round(cramers_v, 4),
            f'Highest %s in {target_col_name} Columns' % target_col_name: str(highest_pct_info),
            f'Lowest %s in {target_col_name} Columns' % target_col_name: str(lowest_pct_info)
        })

    # Convert the list of results into a clean pandas DataFrame
    results_df = pd.DataFrame(results_list)
    return results_df.sort_values(by='P-value')




# 2. Run the function on the entire DataFrame, specifying the target column
summary_table = run_chi_square_for_all_columns(
    df=df_cleaned_missing4,
    target_col_name='mth23',
    alpha=0.05
)

# 3. Display the resulting summary DataFrame
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 200)

print("\n--- Chi-Square Association Summary Table (DataFrame Output) ---\n")
print(summary_table)

"""# Spliting Data Into Three section
1. Depression related(mth1- mth9) & Anxiety related(mth10-mth16)
2. Socio_Demographic Data(v701 to last)
3. Care Seeking behavior or Treament or Target column
"""

mth_data = df_cleaned_missing4.iloc[:, 0:16]
socio_data = df_cleaned_missing4.iloc[:, 22:]
care_seeking_data = df_cleaned_missing4.iloc[:, 16:22]
mth_data.head()

socio_data.head()



care_seeking_data.head()



import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors

# Define the ordinal scale mapping based on the survey (PHQ-9 and GAD-7)
scale_mapper = {
    'never': 0,
    'rarely': 1,
    'often': 2,
    'always': 3
}

# Apply mapping and ensure numeric types, then calculate Spearman correlation
mth_data_numeric = mth_data.astype(object).replace(scale_mapper).apply(pd.to_numeric, errors='coerce')
spearman_corr_mth = mth_data_numeric.corr(method='spearman')

# Create a ListedColormap from the seaborn 'pastel' palette
pastel_cmap = matplotlib.colors.ListedColormap(sns.color_palette('pastel', as_cmap=False))

plt.figure(figsize=(16, 12))
sns.heatmap(spearman_corr_mth, annot=True, cmap=pastel_cmap, fmt=".2f", linewidths=.5)
plt.title('Spearman Correlation Heatmap of Mental Health Variables (mth1-mth16)')
plt.savefig('spearman_correlation_heatmap.pdf')
plt.show()

# Define the ordinal scale mapping based on the survey (PHQ-9 and GAD-7)
scale_mapper = {
    'never': 0,
    'rarely': 1,
    'often': 2,
    'always': 3
}

# Apply mapping and ensure numeric types, then calculate Spearman correlation
mth_data_numeric = mth_data.astype(object).replace(scale_mapper).apply(pd.to_numeric, errors='coerce')
spearman_corr_mth = mth_data_numeric.corr(method='spearman')
display(spearman_corr_mth)

"""# Finding Best Latent classes"""

# Example data (replace with your actual data)
# Data should be integer-encoded and 0-indexed.
scale_mapper = {'never': 0, 'rarely': 1, 'often': 2, 'always': 3}
item_cols = [f'mth{i}' for i in range(1, 17)]
df_lpa = df_cleaned_missing4[item_cols].replace(scale_mapper).apply(pd.to_numeric, errors='coerce').dropna()
data = df_lpa

# Dictionary to store fit statistics
fit_results = []
# Fit models with different numbers of classes (e.g., 2 to 6)
for n_classes in range(2, 7):
    # Initialize and fit the model. Use a sufficient number of reps (n_init)
    # to avoid local optima.
    # Reducing n_init to speed up execution and prevent KeyboardInterrupt
    model = StepMix(n_components=n_classes, measurement="categorical", n_init=5, random_state=42)
    model.fit(data)

    # Store relevant metrics
    fit_results.append({
        'Classes': n_classes,
        'AIC': model.aic(data),
        'BIC': model.bic(data),
        'Log-likelihood': model.score(data), # model.score returns log-likelihood
        'Entropy': model.entropy(data)
    })

# Convert results to a DataFrame for easy comparison
results_df = pd.DataFrame(fit_results)
print(results_df)

# Find the model with the minimum BIC
best_model_bic = results_df.loc[results_df['BIC'].idxmin()]
print(f"\nBest model according to BIC: {best_model_bic['Classes']} classes")

# Visualize the BIC/AIC values (optional, for elbow plot)
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(results_df['Classes'], results_df['BIC'], marker='o', label='BIC')
plt.plot(results_df['Classes'], results_df['AIC'], marker='o', label='AIC')
plt.xlabel('Number of Latent Classes')
plt.ylabel('Criterion Value')
plt.title('Model Fit Criteria by Number of Classes')
plt.legend()
plt.grid(True)
plt.savefig('AIC_BIC_curve.pdf')
plt.show()

# LATENT PROFILE ANALYSIS


import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from scipy.stats import entropy as scipy_entropy

# ----------------------------------------------------------
# 1. Select continuous indicator variables
# ----------------------------------------------------------

scale_mapper = {'never': 0, 'rarely': 1, 'often': 2, 'always': 3}
item_cols = [f'mth{i}' for i in range(1, 17)]
df_lpa = df_cleaned_missing4[item_cols].replace(scale_mapper).apply(pd.to_numeric, errors='coerce').dropna()
lpa_data = df_lpa


# Standardization
scaler = StandardScaler()
X = scaler.fit_transform(lpa_data)

scaler = StandardScaler()
X = scaler.fit_transform(data)

n, p = X.shape

results = []

for k in range(1, 7):
    gmm = GaussianMixture(
        n_components=k,
        covariance_type="diag",
        n_init=100,
        max_iter=2000,
        random_state=123
    )
    gmm.fit(X)

    probs = gmm.predict_proba(X)

    loglik = gmm.score(X) * n
    aic = gmm.aic(X)
    bic = gmm.bic(X)

    # Number of parameters
    n_params = gmm._n_parameters()

    # SABIC (correct)
    sabic = -2 * loglik + np.log((n + 2) / 24) * n_params

    # Correct entropy (0–1)
    entropy = 1 - (
        -np.sum(probs * np.log(probs + 1e-12))
        / (n * np.log(k))
    )

    class_prop = probs.mean(axis=0).min()

    results.append({
        "Classes": k,
        "LogLik": loglik,
        "AIC": aic,
        "BIC": bic,
        "SABIC": sabic,
        "Entropy": entropy,
        "Min_Class_Prop": class_prop
    })

fit_table = pd.DataFrame(results).sort_values("BIC")
print(fit_table.round(3))

"""# Creating Latent Profile"""

# Example data (replace with your actual data)
# Data should be integer-encoded and 0-indexed.
scale_mapper = {'never': 0, 'rarely': 1, 'often': 2, 'always': 3}
item_cols = [f'mth{i}' for i in range(1, 17)]
df_lpa = df_cleaned_missing4[item_cols].replace(scale_mapper).apply(pd.to_numeric, errors='coerce').dropna()
data = df_lpa

# Fit LPA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_lpa)
gmm = GaussianMixture(n_components=3, covariance_type='full', random_state=42)
gmm.fit(X_scaled)
profile_labels = gmm.predict(X_scaled)
# 0_ Resilient Profile
# 1_ Silent Somatic Profile
# 2_Severe Combrid Profile
print(profile_labels)

"""# Multinomial Logistic Regression"""

# --- 2. PREPARE DATA FOR MNLOGIT ---
df_regression = df_cleaned_missing4.loc[df_lpa.index].copy()
df_regression['Profile'] = profile_labels

covariates = ['v190a', 'v106', 'v102'] # Wealth, Education, Residence
df_mnl = df_regression[['Profile'] + covariates].dropna()

# Set the Resilient Profile (Code 1) as the reference category (code 0)
df_mnl['Profile'] = df_mnl['Profile'].astype('category').cat.reorder_categories([1, 0, 2]).cat.codes

# Dummy Encode Covariates
df_mnl = pd.get_dummies(df_mnl, columns=covariates, drop_first=False)

# Define X (Predictors) by explicitly listing non-reference categories (8 columns)
# The successful, explicit column list:
X_cols_final = [
    'v190a_poorest', 'v190a_poorer', 'v190a_middle', 'v190a_richer', # Wealth (4 columns)
    'v106_no education', 'v106_primary', 'v106_secondary',           # Education (3 columns)
    'v102_rural'                                                    # Residence (1 column)
]

X = df_mnl[X_cols_final]
Y = df_mnl['Profile']

# --- 3. RUN MULTINOMIAL LOGISTIC REGRESSION ---
print("--- Running Multinomial Logistic Regression (MNLogit) ---")
try:
    mnl_model = MNLogit(Y, X)
    mnl_fit = mnl_model.fit(method='ncg', maxiter=100, disp=0)

    # 4. OUTPUT RESULTS (P-values and Coefficients)
    print("\n--- Full Regression Summary (P-values and Coefficients) ---")
    print(mnl_fit.summary())

    # --- Odds Ratio (Magnitude and Direction) Calculation ---
    params = mnl_fit.params
    odds_ratios = np.exp(params).round(3)

    results_df = pd.concat([params.round(3), odds_ratios], axis=1)
    results_df.columns = ['Coefficient (Log-Odds)', 'Odds Ratio (OR)']

    print("\n--- Odds Ratios (OR) and Magnitude ---")
    print("Interpretation: OR > 1 means higher odds of target profile vs. Resilient.")
    print(results_df)

except Exception as e:
    print(f"An error occurred during MNLogit fitting. Error: {e}")

"""# Psycometric Network Analysis & Laten Profile Analysis"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.mixture import GaussianMixture
from sklearn.covariance import GraphicalLasso
from sklearn.preprocessing import StandardScaler



# Define the ordinal scale mapping based on the survey (PHQ-9 and GAD-7)
scale_mapper = {
    'never': 0,
    'rarely': 1,
    'often': 2,
    'always': 3
}

# Select the specific Mental Health items
# mth1-mth9 correspond to PHQ-9 (Depression)
# mth10-mth16 correspond to GAD-7 (Anxiety)
item_cols = [f'mth{i}' for i in range(1, 17)]

# Updated clinical labels for better visualization later
item_labels = [
    'Anhedonia', 'Sadness', 'Sleep', 'Fatigue', 'Appetite', 'Guilt',
    'Concentration', 'Motor', 'Suicide', 'Nervousness', 'Control Worry',
    'Excess Worry', 'Relaxation', 'Restlessness', 'Irritability', 'Fear'
]

# Apply mapping and ensure numeric types
df_analysis = df_cleaned_missing4[item_cols].replace(scale_mapper)
df_analysis = df_analysis.apply(pd.to_numeric, errors='coerce')

# Drop any rows with missing values to ensure clean analysis
df_analysis = df_analysis.dropna()

print(f"Final sample size for analysis: {len(df_analysis)}")

# Standardize data (Z-scores) - Crucial for LPA and Network Analysis
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_analysis)

# ==========================================
# 2. PSYCHOMETRIC NETWORK ANALYSIS (PNA)
# ==========================================
# We use Graphical Lasso to estimate the precision matrix (inverse covariance)
# This models the partial correlations between symptoms (the "edges" in the network)
glasso = GraphicalLasso(alpha=0.01, mode='cd', tol=1e-4, max_iter=100)
glasso.fit(X_scaled)
precision_matrix = glasso.precision_

# Calculate "Node Centrality" (Strength)
# Strength = sum of absolute partial correlations for each node (excluding self-loops)
# This identifies which symptom is the "driver" of the network
net_matrix = precision_matrix.copy()
np.fill_diagonal(net_matrix, 0) # Remove diagonal (self-correlation)
centrality = np.sum(np.abs(net_matrix), axis=1)

# Organize Centrality Data
centrality_df = pd.DataFrame({
    'Symptom': item_labels,
    'Centrality_Strength': centrality
}).sort_values('Centrality_Strength', ascending=False)

print("\n--- Network Centrality Findings ---")
print(centrality_df.head(5)) # The top items are your "Bridge Symptoms"

# Plot Centrality
plt.figure(figsize=(10, 6))
sns.barplot(x='Centrality_Strength', y='Symptom', data=centrality_df, palette='pastel', hue='Symptom', legend=False)
plt.title("Symptom Centrality: Identifying the 'Drivers' of Mental Distress")
plt.xlabel("Strength (Sum of Partial Correlations)")
plt.savefig('symptom_centrality.pdf')
plt.show()

# ==========================================
# 3. LATENT PROFILE ANALYSIS (LPA)
# ==========================================
# We use Gaussian Mixture Modeling to find hidden subgroups (Profiles)
# Based on our finding, 3 components provided the best fit
n_profiles = 3
gmm = GaussianMixture(n_components=n_profiles, covariance_type='full', random_state=42)
gmm.fit(X_scaled)

# Assign each woman to a profile
df_analysis['Profile'] = gmm.predict(X_scaled)

# Calculate the mean scores for each item per profile (to interpret what they mean)
# We convert back to original scale (0-3) for easier interpretation
profile_means = df_analysis.groupby('Profile')[item_cols].mean()

print("\n--- Latent Profile Descriptions ---")
print(profile_means)

# Plot the Profiles
plt.figure(figsize=(14, 6))
# Create a custom color palette for the 3 groups
colors = ['green', 'orange', 'red']
profile_names = ['Profile A (Resilient)', 'Profile B (Silent Somatic)', 'Profile C (Severe)']

for i in range(n_profiles):
    plt.plot(item_labels, profile_means.iloc[i], marker='o', linewidth=2,
             label=profile_names[i], color=colors[i])

plt.xticks(rotation=45)
plt.ylabel('Mean Symptom Score (0 = Never, 3 = Always)')
plt.title('Latent Profiles: Visualizing the "Silent Somatic" Phenotype')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.savefig('latent_profiles_visualisation.pdf')
plt.show()

"""# Labeling Mth variables

| Variable Code | Scale Item | Standard Question Text (BDHS)                     | Clinical Label (Node Name) |
|---------------|------------|---------------------------------------------------|----------------------------|
|               |            | **Depression (PHQ-9)**                            |                            |
| mth1          | PHQ-1      | Little interest or pleasure in doing things       | Anhedonia                  |
| mth2          | PHQ-2      | Feeling down, depressed, or hopeless              | Sadness                    |
| mth3          | PHQ-3      | Trouble falling/staying asleep, sleeping too much | Sleep                      |
| mth4          | PHQ-4      | Feeling tired or having little energy             | Fatigue                    |
| mth5          | PHQ-5      | Poor appetite or overeating                       | Appetite                   |
| mth6          | PHQ-6      | Feeling bad about yourself / failure              | Guilt                      |
| mth7          | PHQ-7      | Trouble concentrating on things                   | Concentration              |
| mth8          | PHQ-8      | Moving/speaking slowly or too fast                | Motor                      |
| mth9          | PHQ-9      | Thoughts of being better off dead                 | Suicide                    |
|               |            | **Anxiety (GAD-7)**                               |                            |
| mth10         | GAD-1      | Feeling nervous, anxious, or on edge              | Nervousness                |
| mth11         | GAD-2      | Not being able to stop or control worrying        | Control Worry              |
| mth12         | GAD-3      | Worrying too much about different things          | Excess Worry               |
| mth13         | GAD-4      | Trouble relaxing                                  | Relaxation                 |
| mth14         | GAD-5      | Being so restless that it is hard to sit still    | Restlessness               |
| mth15         | GAD-6      | Becoming easily annoyed or irritable              | Irritability               |
| mth16         | GAD-7      | Feeling afraid as if something awful might happen | Fear                       |

# CS-Coefficient and Stability Plot
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.covariance import GraphicalLassoCV
from sklearn.preprocessing import StandardScaler
from scipy.stats import spearmanr

# 1. SETUP FUNCTIONS
def estimate_strength(data):
    """Estimates the strength centrality of a network using Glasso"""
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(data)

    # Estimate partial correlations using GraphicalLasso
    model = GraphicalLassoCV(cv=5)
    model.fit(X_scaled)
    precision = model.precision_

    # Convert to partial correlation matrix
    d = np.sqrt(np.diag(precision))
    pcorr = -precision / np.outer(d, d)
    np.fill_diagonal(pcorr, 1)

    # Node Strength: Sum of absolute values of connections
    return np.sum(np.abs(pcorr), axis=1) - 1

# 2. DATA PREPARATION
# Load your mth1-mth16 variables here
# df_symptoms = pd.read_stata('mental_processed_dataset.dta')[items]
# For this example, we assume X_symptoms is already defined from your previous steps

# 3. ORIGINAL STRENGTH
original_strength = estimate_strength(df_analysis)

# 4. CASE-DROPPING BOOTSTRAP
percentages = [0.95, 0.90, 0.80, 0.70, 0.50, 0.25] # Percentage of sample kept
n_iterations = 10 # For Q1 paper, use at least 100-500. Using 10 here for speed.
stability_results = []

print("Starting Stability Bootstrap...")
for p in percentages:
    correlations = []
    n_subsample = int(len(df_mnl) * p)

    for i in range(n_iterations):
        # Randomly sample cases
        subsample = df_analysis.sample(n=n_subsample, replace=False)
        try:
            sub_strength = estimate_strength(subsample)
            # Calculate Spearman correlation between original and subsample rankings
            corr, _ = spearmanr(original_strength, sub_strength)
            correlations.append(corr)
        except:
            continue

    stability_results.append({'proportion_kept': p, 'mean_corr': np.mean(correlations)})

# 5. CALCULATE CS-COEFFICIENT
# The CS-coefficient is the maximum proportion of cases that can be dropped
# while maintaining a correlation of > 0.7 with the original sample.
stability_df = pd.DataFrame(stability_results)
cs_threshold = 0.7
# Find the lowest proportion where mean_corr is still > 0.7
safe_drop = stability_df[stability_df['mean_corr'] >= cs_threshold]
cs_coeff = 1 - safe_drop['proportion_kept'].min() if not safe_drop.empty else 0

print(f"\nCalculated CS-coefficient (Strength): {cs_coeff:.3f}")

# 6. VISUALIZE STABILITY (For your paper's Appendix)

plt.figure(figsize=(8, 5))
plt.plot(stability_df['proportion_kept'], stability_df['mean_corr'], marker='o', color='teal')
plt.axhline(y=0.7, color='r', linestyle='--', label='Threshold (0.7)')
plt.title('Network Centrality Stability (Case-dropping Bootstrap)')
plt.xlabel('Proportion of Sample Retained')
plt.ylabel('Correlation with Original Centrality')
plt.gca().invert_xaxis() # Show dropping from 100% to 25%
plt.legend()
plt.grid(True)
plt.show()